Repository elastic/apm-agent-php, pull requests merged in 2020-11, with the labels that each got.

#261 Document TRANSACTION_MAX_SPANS configuration option
  docs/configuration.asciidoc
Labels: documentation

#266 [CI] remove unused stages
  .ci/Jenkinsfile
Labels: automation, ci

#267 [CI] split static check with unit and component tests
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/component-test.sh
  .ci/static-check-unit-test.sh
  DEVELOPMENT.md
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: automation

#265 [CI] run cmocka as part of the static-check-unit-test stage
  .ci/Jenkinsfile
  .ci/static-check-unit-test.sh
  .gitignore
  Dockerfile
  Dockerfile.alpine
Labels: automation, ci

#271 [CI] Transform phpstan to junit
  .ci/static-check-unit-test.sh
  composer.json
Labels: automation, ci, team:automation

#274 [CI] PHPUnit to JUnit
  .ci/Jenkinsfile
  .ci/loop.sh
  .gitignore
  phpunit.xml.dist
  phpunit_component_tests.xml
Labels: automation, ci

#270 [CI] cache docker images
  .ci/packer_cache.sh
Labels: automation, ci

#278 Enabled PHPUnit's feature of spawning a separate process for each unit test
  phpunit.xml.dist
  tests/ElasticApmTests/TestsSharedCode/TransactionMaxSpansTest/SharedCode.php
  tests/ElasticApmTests/UnitTests/LogTests/LoggingVariousTypesTest.php
Labels: testing

#281 Added ELASTIC_APM_PHP_TESTS_FLAKY_ASSERTIONS_ENABLED env var
  tests/ElasticApmTests/ComponentTests/Util/FlakyAssertions.php
  tests/ElasticApmTests/ComponentTests/Util/PhpUnitExtension.php
  tests/ElasticApmTests/ComponentTests/Util/TempDisableFailingAssertions.php
  tests/ElasticApmTests/Util/TestCaseBase.php
Labels: automation, flaky test, testing

#283 Added support for distributed tracing
  examples/ElasticApmExamples/UsingPublicApi/ExampleUsingPublicApi.php
  src/ElasticApm/AutoInstrument/InterceptedCallTrackerInterface.php
  src/ElasticApm/AutoInstrument/PluginInterface.php
  src/ElasticApm/AutoInstrument/RegistrationContextInterface.php
  src/ElasticApm/DistributedTracingData.php
  src/ElasticApm/ElasticApm.php
  src/ElasticApm/ExecutionSegmentContextInterface.php
  src/ElasticApm/ExecutionSegmentInterface.php
  src/ElasticApm/Impl/AutoInstrument/BuiltinPlugin.php
  src/ElasticApm/Impl/AutoInstrument/CurlAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/InterceptionManager.php
  src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php
  src/ElasticApm/Impl/ExecutionSegment.php
  src/ElasticApm/Impl/HttpDistributedTracing.php
  src/ElasticApm/Impl/Log/LogCategory.php
  src/ElasticApm/Impl/Log/SinkBase.php
  src/ElasticApm/Impl/NoopExecutionSegment.php
  src/ElasticApm/Impl/NoopTracer.php
  src/ElasticApm/Impl/NoopTransaction.php
  src/ElasticApm/Impl/Span.php
  src/ElasticApm/Impl/Tracer.php
  src/ElasticApm/Impl/TracerInterface.php
  src/ElasticApm/Impl/Transaction.php
  src/ElasticApm/Impl/Util/IdValidationUtil.php
  src/ElasticApm/SpanContextInterface.php
  src/ElasticApm/TransactionContextInterface.php
  src/ElasticApm/TransactionInterface.php
  tests/ElasticApmTests/ComponentTests/Util/ResourcesCleaner.php
  tests/ElasticApmTests/UnitTests/CapturePublicApiTest.php
  tests/ElasticApmTests/UnitTests/ExamplePublicApiElasticApmTest.php
  tests/ElasticApmTests/UnitTests/GlobalTracerTest.php
  tests/ElasticApmTests/UnitTests/HttpDistributedTracingTest.php
  tests/ElasticApmTests/UnitTests/LoggingVariousEventTypesTest.php
  tests/ElasticApmTests/UnitTests/NoopEventsTest.php
  tests/ElasticApmTests/UnitTests/PublicApiTest.php
  tests/ElasticApmTests/UnitTests/SamplingUnitTest.php
  tests/ElasticApmTests/UnitTests/ServerApiSchemaValidationTest.php
  tests/ElasticApmTests/UnitTests/StacktraceUnitTest.php
  tests/ElasticApmTests/UnitTests/TimeRelatedApiUsingMockClockTest.php
  tests/ElasticApmTests/UnitTests/TimeRelatedApiUsingRealClockTest.php
  tests/ElasticApmTests/UnitTests/TransactionMaxSpansUnitTest.php
  tests/ElasticApmTests/UnitTests/Util/NotFoundException.php
  tests/ElasticApmTests/UnitTests/Util/TracerUnitTestCaseBase.php
  tests/ElasticApmTests/Util/DummyExceptionForTests.php
  tests/ElasticApmTests/Util/TestCaseBase.php
  tests/ElasticApmTests/Util/ValidationUtil.php
Labels: cross APM agents, enhancement

#285 Exclude query string from a transaction name
  src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php
  src/ElasticApm/Impl/Util/UrlUtil.php
Labels: bug

#277 Documentation changes for "setLabel() have been moved to under context()"
  docs/public-api.asciidoc
Labels: documentation

#288 Add spans for various PDO methods
  src/ElasticApm/Impl/AutoInstrument/CurlAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/CurlHandleTracker.php
  src/ElasticApm/Impl/AutoInstrument/InterceptedCallTrackerTrait.php
  src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php
  src/ElasticApm/Impl/ErrorExceptionData.php
Labels: technical debt

#289 [CI] Fix the single quote issue when raising PRs
  .ci/Jenkinsfile
Labels: automation, ci

#291 [CI] Push with the step
  .ci/Jenkinsfile
Labels: automation, ci

#292 [RELEASE] 1.0.0-beta1
  CHANGELOG.asciidoc
  src/ElasticApm/ElasticApm.php
  src/ext/elastic_apm_version.h
Labels: changelog, docs, release

#293 [CI] speed builds, component tests run in the packaging
  .ci/Jenkinsfile
  DEVELOPMENT.md
  packaging/Makefile
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: automation, ci

#295 [CI] Add clarity to the APM-ITS GitHub check
  .ci/Jenkinsfile
Labels: automation, ci
