Repository elastic/apm-agent-php, pull requests merged in 2020-08, with the labels that each got.

#115 [CI] Cosmetic changes in the stage names
  .ci/Jenkinsfile
Labels: automation, ci

#116 [Packaging] restore php.ini if something bad happened
  packaging/post-install.sh
Labels: automation

#121 [packaging] support multiple PHP API
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/generate-for-package.sh
  DEVELOPMENT.md
  packaging/Makefile
  packaging/post-install.sh
  packaging/test/centos/Dockerfile
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/Dockerfile
  packaging/test/ubuntu/entrypoint.sh
Labels: automation, enhancement

#128 Change composer installation in docker
  Dockerfile
  packaging/test/centos/Dockerfile
  packaging/test/ubuntu/Dockerfile
Labels: automation, bug

#92 Support APK with FPM
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/generate-for-package.sh
  .gitignore
  DEVELOPMENT.md
  Dockerfile.alpine
  packaging/Dockerfile
  packaging/Makefile
  packaging/create-package.sh
  packaging/fpm_apm.patch
  packaging/post-install.sh
  packaging/test/alpine/Dockerfile
  packaging/test/alpine/entrypoint.sh
  src/ext/platform.c
  src/ext/platform.h
Labels: automation

#141 [packaging] include C source file from .so is built
  packaging/create-package.sh
Labels: automation

#148 [CI] Archive PHPUnit Tests results
  .ci/Jenkinsfile
Labels: automation, ci

#122 [CI] Automate release to GitHub
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/release.sh
  DEVELOPMENT.md
Labels: automation, ci

#150 [CI] fix post caused by a wrong auto-merge
  .ci/Jenkinsfile
Labels: automation

#167 docs: prepare for doc build
  CHANGELOG.asciidoc
  docs/index.asciidoc
  docs/page_header.html
  docs/release-notes.asciidoc
Labels: documentation
