Repository elastic/apm-agent-php, pull requests merged in 2020-09, with the labels that each got.

#177 [CI] enable package archiving
  .ci/Jenkinsfile
  README.md
Labels: automation, ci

#180 Update "Configuration reference" section of the documentation
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  docs/intro.asciidoc
  docs/public-api.asciidoc
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
Labels: documentation

#181 [DOCS] Artifacts badge
  README.md
Labels: automation

#182 [CI] run whole build for branches/tags when only DOCS
  .ci/Jenkinsfile
Labels: automation, ci

#186 [packaging] generate-for-package does not use make install
  .ci/Makefile
Labels: automation

#172 [CI] sign artifacts for the release (partially implemented)
  .ci/Jenkinsfile
Labels: automation

#194 [CI] test signed binaries and released binaries
  .ci/Jenkinsfile
  DEVELOPMENT.md
  packaging/Makefile
  packaging/test/alpine/Dockerfile
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/Dockerfile
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/Dockerfile
  packaging/test/ubuntu/entrypoint.sh
Labels: automation

#201 docs: Link to docs from readme
  README.md
Labels: documentation
