Repository elastic/apm-agent-php, pull requests merged in 2020-10, with the labels that each got.

#197 [DOCS] Add latest release badge
  README.md
Labels: automation, documentation

#204 [CI][RELEASE] notify when a tag release is created
  .ci/Jenkinsfile
Labels: automation, ci

#209 Sort config doc alphabetically
  docs/configuration.asciidoc
Labels: documentation

#200 [CI] Release from the UI
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/bump_version.sh
  .gitignore
Labels: automation, ci

#215 [DOCS] Changelog generation
  .ci/.grenrc.js
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/docker/gren/Dockerfile
  .ci/release.sh
  CHANGELOG.asciidoc
Labels: automation, documentation

#219 [CI] Use PR URL in the notifications
  .ci/Jenkinsfile
Labels: automation, ci, release

#222 [Packaging] support uninstalling package
  .ci/Jenkinsfile
  packaging/Makefile
  packaging/before-uninstall.sh
  packaging/create-package.sh
  packaging/post-install.sh
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: automation

#225 Added VERIFY_SERVER_CERT configuration option
  src/ElasticApm/Impl/Config/AllOptionsMetadata.php
  src/ElasticApm/Impl/Config/OptionNames.php
  src/ElasticApm/Impl/Config/Snapshot.php
  src/ext/ConfigManager.c
  src/ext/ConfigManager.h
  src/ext/ResultCode.h
  src/ext/backend_comm.c
  src/ext/elastic_apm.c
  src/ext/log.c
  tests/ElasticApmTests/ComponentTests/ApiKeyTest.php
  tests/ElasticApmTests/ComponentTests/MetadataTest.php
  tests/ElasticApmTests/ComponentTests/SamplingTest.php
  tests/ElasticApmTests/ComponentTests/SecretTokenTest.php
  tests/ElasticApmTests/ComponentTests/Util/CliScriptTestEnv.php
  tests/ElasticApmTests/ComponentTests/Util/ComponentTestCaseBase.php
  tests/ElasticApmTests/ComponentTests/Util/ConfigSetterBase.php
  tests/ElasticApmTests/ComponentTests/Util/ConfigSetterEnvVars.php
  tests/ElasticApmTests/ComponentTests/Util/PhpUnitExtension.php
  tests/ElasticApmTests/ComponentTests/Util/TestEnvBase.php
  tests/ElasticApmTests/ComponentTests/Util/TestProcessUtil.php
  tests/ElasticApmTests/ComponentTests/Util/TestProperties.php
  tests/ElasticApmTests/ComponentTests/VerifyServerCertTest.php
Labels: cross APM agents, enhancement

#228 Added check that the corresponding extension is loaded before instrumenting it
  src/ElasticApm/Impl/AutoInstrument/CurlAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/RegistrationContext.php
Labels: bug

#226 Document VERIFY_SERVER_CERT configuration option
  docs/configuration.asciidoc
Labels: documentation

#229 Miscellaneous documentation improvements
  docs/configuration.asciidoc
  docs/setup.asciidoc
  src/ext/elastic_apm.ini
Labels: documentation

#232 Automatically capture stack trace for spans
  .editorconfig
  phpstan.neon
  src/ElasticApm/AutoInstrument/InterceptedCallTrackerInterface.php
  src/ElasticApm/Impl/AutoInstrument/CurlAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/InterceptedCallTrackerTrait.php
  src/ElasticApm/Impl/AutoInstrument/InterceptionManager.php
  src/ElasticApm/Impl/AutoInstrument/PdoAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php
  src/ElasticApm/Impl/ExecutionSegmentTrait.php
  src/ElasticApm/Impl/NoopExecutionSegment.php
  src/ElasticApm/Impl/NoopSpan.php
  src/ElasticApm/Impl/ServerComm/SerializationUtil.php
  src/ElasticApm/Impl/Span.php
  src/ElasticApm/Impl/SpanData.php
  src/ElasticApm/Impl/Transaction.php
  src/ElasticApm/Impl/Util/TextUtil.php
  src/ElasticApm/SpanDataInterface.php
  src/ElasticApm/SpanInterface.php
  src/ElasticApm/StacktraceFrame.php
  tests/ElasticApmTests/ComponentTests/StacktraceComponentTest.php
  tests/ElasticApmTests/ComponentTests/Util/AmbientContext.php
  tests/ElasticApmTests/ComponentTests/Util/ComponentTestCaseBase.php
  tests/ElasticApmTests/UnitTests/StacktraceTestSharedCode.php
  tests/ElasticApmTests/UnitTests/StacktraceUnitTest.php
  tests/ElasticApmTests/Util/Deserialization/SpanDataDeserializer.php
  tests/ElasticApmTests/Util/Deserialization/StacktraceDeserializer.php
  tests/ElasticApmTests/Util/TestCaseBase.php
  tests/ElasticApmTests/Util/TestLogSink.php
  tests/ElasticApmTests/Util/ValidationUtil.php
  tests/ElasticApmTests/dummyFuncForTestsWithNamespace.php
  tests/bootstrap.php
  tests/dummyFuncForTestsWithoutNamespace.php
Labels: enhancement

#235 Fixed Span::endSpanEx to have consistent meaning for numberOfStackFramesToSkip
  src/ElasticApm/Impl/AutoInstrument/InterceptedCallTrackerTrait.php
  src/ElasticApm/Impl/ExecutionSegmentTrait.php
  src/ElasticApm/Impl/NoopSpan.php
  src/ElasticApm/Impl/Span.php
  src/ElasticApm/Impl/Transaction.php
  src/ElasticApm/SpanInterface.php
Labels: technical debt

#234 Fixed issues with syslog for docker containers used for testing
  .ci/composer.sh
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: automation, developer only, testing

#236 ci(jenkins): trigger async ITs and update github check for the pull request
  .ci/Jenkinsfile
Labels: automation, ci

#241 [CI] enable test reporting for flaky results
  .ci/Jenkinsfile
Labels: automation, ci

#240 [packaging] uninstallation support for alpine
  packaging/before-uninstall.sh
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: automation, bug

#250 [CI] increase number of loops and store tests
  .ci/loop.groovy
  .ci/loop.sh
Labels: automation

#251 [CI] skip on a PR basis
  .ci/jobs/loop-mbp.yml
  .ci/loop.groovy
Labels: automation, bug

#252 [CI] typo in the upstream folder name
  .ci/loop.groovy
Labels: automation, bug, ci

#249 Document SERVER_TIMEOUT configuration option
  docs/configuration.asciidoc
Labels: documentation

#254 [CI] changelog automation
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/docker/gren/Dockerfile
  .ci/docker/gren/entrypoint.sh
Labels: automation, ci, release

#256 [CI] changelog follow ups
  .ci/.grenrc.js
  .ci/Jenkinsfile
  .ci/docker/gren/entrypoint.sh
Labels: automation, ci

#257 Changelog generation formatted with header 3
  .ci/.grenrc.js
Labels: automation
