Repository elastic/apm-agent-php, pull requests merged in 2021-07, with the labels that each got.

#452 Increase stage timeout to 2 hours
  .ci/Jenkinsfile
Labels: agent-php

#453 [backport to 1.x] Increase stage timeout to 2 hours
  .ci/Jenkinsfile
Labels: agent-php

#457 CI: archive so files to be downloaded if needed
  .ci/Jenkinsfile
Labels: agent-php, automation, developer only

#455 [packaging] Support upgrade in RPM
  .ci/Jenkinsfile
  DEVELOPMENT.md
  packaging/Makefile
  packaging/before-uninstall.sh
  packaging/post-install.sh
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: agent-php

#451 test: synchronizing json spec
  tests/APM_Agents_shared/json-specs/w3c_distributed_tracing.json
Labels: agent-php, automation

#456 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/span.json
Labels: agent-php, automation
