Repository elastic/apm-agent-php, pull requests merged in 2021-05, with the labels that each got.

#410 Improved supportability info formatting
  src/ext/ConfigManager.c
  src/ext/ConfigManager.h
  src/ext/supportability.c
Labels: agent-php, developer only

#413 changelog: fix duplicated entries
  .ci/docker/gren/Dockerfile
Labels: agent-php, automation

#416 Updated CI scripts to include PHP version 8.0
  .ci/Jenkinsfile
  .ci/loop.groovy
  .ci/packer_cache.sh
  composer.json
  packaging/post-install.sh
  packaging/test/alpine/Dockerfile
  packaging/test/centos/Dockerfile
  packaging/test/ubuntu/Dockerfile
  src/ElasticApm/Impl/AutoInstrument/CurlAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/CurlHandleTracker.php
  src/ext/ConfigManager.c
  src/ext/SystemMetrics.c
  src/ext/elastic_apm.c
  src/ext/tracer_PHP_part.c
  src/ext/util_for_PHP.c
  src/ext/util_for_PHP.h
Labels: agent-php

#418 [ci] 50 loops and 7 hours
  .ci/loop.groovy
Labels: Team:Automation, agent-php, automation
