Repository elastic/apm-agent-php, pull requests merged in 2021-03, with the labels that each got.

#358 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/metadata.json
  tests/APM_Server_intake_API_schema/latest_used/metricset.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: agent-php, automation

#366 Update PHPStan to 0.12.80
  composer.json
Labels: developer only

#368 test: synchronizing gherkin spec
  tests/APM_Agents_shared/gherkin-specs/azure_app_service_metadata.feature
Labels: agent-php, automation

#369 test: synchronizing gherkin spec
  tests/APM_Agents_shared/gherkin-specs/azure_app_service_metadata.feature
Labels: agent-php, automation

#371 Added check if $_SERVER is set before using it
  src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php
Labels: agent-php

#373 ci: increase timeout
  .ci/loop.groovy
Labels: agent-php, automation

#374 ci: use the new flaky analyser
  .ci/Jenkinsfile
Labels: agent-php, automation, ci

#377 docs: remove beta warning
  docs/page_header.html
Labels: agent-php, docs

#378 Updated Supported technologies
  docs/setup.asciidoc
  docs/supported-technologies.asciidoc
Labels: agent-php, documentation

#379 [RELEASE] 1.0.0
  CHANGELOG.asciidoc
  src/ElasticApm/ElasticApm.php
  src/ext/elastic_apm_version.h
Labels: agent-php, changelog, docs, release

#380 [ci] improve release notifications with earlier feedback and set the description
  .ci/Jenkinsfile
Labels: ci
