Repository elastic/apm-agent-php, pull requests merged in 2021-06, with the labels that each got.

#421 Add PHP 8.0 to supported versions
  docs/supported-technologies.asciidoc
Labels: agent-php

#420 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/metricset.json
Labels: agent-php, automation

#434 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/span.json
Labels: agent-php, automation

#438 Document breakdown metrics
  docs/configuration.asciidoc
Labels: agent-php, documentation

#441 Added outcome for transactions and spans
  src/ElasticApm/ExecutionSegmentInterface.php
  src/ElasticApm/Impl/AutoInstrument/CurlHandleTracker.php
  src/ElasticApm/Impl/AutoInstrument/TransactionForExtensionRequest.php
  src/ElasticApm/Impl/Constants.php
  src/ElasticApm/Impl/ExecutionSegment.php
  src/ElasticApm/Impl/ExecutionSegmentData.php
  src/ElasticApm/Impl/NoopExecutionSegment.php
  tests/ElasticApmTests/ComponentTests/HttpTransactionTest.php
  tests/ElasticApmTests/ComponentTests/Util/MockApmServer.php
  tests/ElasticApmTests/UnitTests/DistributedTracingTest.php
  tests/ElasticApmTests/UnitTests/PublicApiTest.php
  tests/ElasticApmTests/Util/Deserialization/ExecutionSegmentDataDeserializer.php
  tests/ElasticApmTests/Util/ValidationUtil.php
Labels: agent-php

#449 Fixed failing component tests
  tests/ElasticApmTests/ComponentTests/ConfigSettingTest.php
  tests/ElasticApmTests/ComponentTests/Util/FlakyAssertions.php
  tests/ElasticApmTests/ComponentTests/Util/ResourcesCleaner.php
  tests/ElasticApmTests/ComponentTests/Util/SpawnedProcessBase.php
  tests/ElasticApmTests/ComponentTests/Util/StatefulHttpServerProcessBase.php
  tests/ElasticApmTests/ComponentTests/Util/TestProcessUtil.php
  tests/ElasticApmTests/ComponentTests/Util/routeToCliBuiltinHttpServerAppCodeHost.php
Labels: agent-php

#450 Bump maximum supported PHP version
  docs/setup.asciidoc
Labels: agent-php
