Repository elastic/apm-agent-php, pull requests merged in 2021-01, with the labels that each got.

#310 [packaging] configure ini files in conf.d
  .ci/Jenkinsfile
  packaging/Makefile
  packaging/before-uninstall.sh
  packaging/create-package.sh
  packaging/post-install.sh
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: agent-php, automation

#317 [packaging] Support default template
  packaging/create-package.sh
  packaging/elastic-apm-custom-template.ini
Labels: agent-php, automation

#326 [CI][loop] Use the right make goals
  .ci/loop.sh
Labels: agent-php, automation, ci

#311 [packaging] configure apache2
  .ci/Jenkinsfile
  .ci/packer_cache.sh
  packaging/Makefile
  packaging/before-uninstall.sh
  packaging/post-install.sh
  packaging/test/ubuntu/apache/Dockerfile
Labels: agent-php, automation, team:automation

#325 [CI][docker] refactoring composer installation
  Dockerfile
  Dockerfile.alpine
  packaging/test/alpine/Dockerfile
  packaging/test/centos/Dockerfile
  packaging/test/ubuntu/Dockerfile
Labels: agent-php, automation, team:automation

#329 Removed NOTICE log level
  docs/configuration.asciidoc
  src/ElasticApm/Impl/AutoInstrument/BootstrapStageLogger.php
  src/ElasticApm/Impl/AutoInstrument/CurlAutoInstrumentation.php
  src/ElasticApm/Impl/AutoInstrument/PhpPartFacade.php
  src/ElasticApm/Impl/ExecutionSegment.php
  src/ElasticApm/Impl/Log/Level.php
  src/ElasticApm/Impl/Log/Logger.php
  src/ext/elastic_apm.c
  src/ext/elastic_apm.ini
  src/ext/log.c
  src/ext/log.h
  src/ext/tests/config_type_LogLevel_is_case_insensitive.phpt
  src/ext/unit_tests/Logger_tests.c
  tests/ElasticApmTests/ComponentTests/Util/SpawnedProcessBase.php
  tests/ElasticApmTests/ComponentTests/Util/StatefulHttpServerProcessBase.php
  tests/ElasticApmTests/ComponentTests/Util/TestEnvBase.php
  tests/ElasticApmTests/Util/LogSinkForTests.php
Labels: agent-php, breaking

#324 [packaging] configure fpm
  .ci/Jenkinsfile
  packaging/Makefile
  packaging/before-uninstall.sh
  packaging/post-install.sh
  packaging/test/ubuntu/fpm/Dockerfile
Labels: agent-php, automation, team:automation

#330 [packaging] detect php version during the installation
  packaging/post-install.sh
Labels: agent-php

#331 Added createCustomError public API
  src/ElasticApm/CustomErrorData.php
  src/ElasticApm/ElasticApm.php
  src/ElasticApm/ExecutionSegmentInterface.php
  src/ElasticApm/Impl/AutoInstrument/InterceptedCallTrackerTrait.php
  src/ElasticApm/Impl/ErrorData.php
  src/ElasticApm/Impl/ErrorExceptionData.php
  src/ElasticApm/Impl/ExecutionSegment.php
  src/ElasticApm/Impl/NoopExecutionSegment.php
  src/ElasticApm/Impl/NoopTracer.php
  src/ElasticApm/Impl/Span.php
  src/ElasticApm/Impl/Tracer.php
  src/ElasticApm/Impl/TracerInterface.php
  src/ElasticApm/Impl/Transaction.php
  tests/ElasticApmTests/UnitTests/CreateErrorTest.php
Labels: agent-php
