Repository elastic/apm-agent-php, pull requests merged in 2021-09, with the labels that each got.

#540 Fixed unit test failing because digits only transaction IDs
  tests/ElasticApmTests/UnitTests/DistributedTracingTest.php
  tests/ElasticApmTests/Util/TestCaseBase.php
Labels: agent-php

#541 Documented SERVICE_NODE_NAME
  docs/configuration.asciidoc
Labels: documentation, agent-php

#543 Added reference to 1.3 section of CHANGELOG to release-notes
  docs/release-notes.asciidoc
Labels: documentation, agent-php

#538 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#545 test: synchronizing json spec
  tests/APM_Agents_shared/json-specs/span_types.json
Labels: automation, agent-php

#546 test: synchronizing json spec
  tests/APM_Agents_shared/json-specs/span_types.json
Labels: automation, agent-php

#549 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/metadata.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#553 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: automation, agent-php

#554 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php
