Repository elastic/apm-agent-php, pull requests merged in 2022-03, with the labels that each got.

#630 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#638 ci: dynamic stages
  .ci/Jenkinsfile
  .ci/generate_stages_list.sh
Labels: automation, Team:Automation, agent-php

#643 ci: split lifecycle-testing in component-test for cli and http
  .ci/Jenkinsfile
  .ci/generate_stages_list.sh
  composer.json
  packaging/Makefile
  packaging/test/alpine/entrypoint.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: automation, Team:Automation, agent-php

#652 Prepare for v1.5 release
  CHANGELOG.asciidoc
  docs/release-notes.asciidoc
  src/ElasticApm/ElasticApm.php
  src/ext/elastic_apm_version.h
Labels: agent-php

#640 test: synchronizing gherkin spec
  tests/APM_Agents_shared/gherkin-specs/otel_bridge.feature
Labels: automation, agent-php

#642 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#650 test: synchronizing gherkin spec
  tests/APM_Agents_shared/gherkin-specs/otel_bridge.feature
Labels: automation, agent-php

#648 ci: speed up release tags
  .ci/Jenkinsfile
Labels: automation, agent-php

#653 ci: change message for tag releases
  .ci/Jenkinsfile
Labels: automation, agent-php

#654 release: add release info
  .ci/release.sh
Labels: agent-php

#656 release: add sleep
  .ci/release.sh
Labels: agent-php

#655 release: rename stages and notifications
  .ci/Jenkinsfile
Labels: agent-php

#658 ci: stage approval after the tests and more parallel stages for the test signed meta-stage
  .ci/Jenkinsfile
  .ci/generate_stages_list_smoke.sh
Labels: automation, agent-php
