Repository elastic/apm-agent-php, pull requests merged in 2022-05, with the labels that each got.

#670 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#671 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#675 Fixed synchronize schema spec merges
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: agent-php

#664 Update: configuration.asciidoc
  docs/configuration.asciidoc
Labels: agent-php

#676 Ported "Update: configuration.asciidoc #664" to main
  docs/configuration.asciidoc
Labels: agent-php

#680 Added diagnostics for failed call to php_stream_open_for_zend_ex()
  src/ext/util_for_PHP.c
Labels: enhancement, agent-php

#681 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/span.json
Labels: automation, agent-php

#685 synchronize schema spec
  tests/APM_Server_intake_API_schema/latest_used/error.json
  tests/APM_Server_intake_API_schema/latest_used/span.json
  tests/APM_Server_intake_API_schema/latest_used/transaction.json
Labels: automation, agent-php

#686 Added docs Prerequisites section
  docs/setup.asciidoc
Labels: documentation, agent-php, docs, Team:Docs

#693 Prepare for v1.5.1 release
  CHANGELOG.asciidoc
  docs/release-notes.asciidoc
  src/ElasticApm/ElasticApm.php
  src/ext/elastic_apm_version.h
Labels: agent-php

#689 test: synchronizing gherkin spec
  tests/APM_Agents_shared/gherkin-specs/otel_bridge.feature
Labels: automation, agent-php

#690 test: synchronizing json spec
  tests/APM_Agents_shared/json-specs/service_resource_inference.json
Labels: automation, agent-php
