Repository elastic/apm-agent-php, pull requests merged in 2023-05, with the labels that each got.

#953 Fixed addDelayToAbsTimeSpec for the case when
  src/ext/time_util.c
  src/ext/unit_tests/time_util_tests.c
Labels: agent-php

#942 [Automation] Update Gherkin specs
  tests/APM_Agents_shared/gherkin-specs/otel_bridge.feature
Labels: automation, agent-php

#956 Fixed line endings (CRLF -> LF)
  src/ext/backend_comm.c
  src/ext/lifecycle.h
  src/ext/tracer_PHP_part.h
Labels: agent-php

#959 Fixed not joining background sender thread if there was fork after module init
  src/ext/lifecycle.c
Labels: agent-php

#957 Fixed not cleaning up connection data in sync backend comm. mode
  src/ext/backend_comm.c
Labels: agent-php

#965 Fixed verify_server_cert=false not disabling all the checks related to HTTPS certificate
  src/ext/backend_comm.c
Labels: agent-php

#955 Prevent deadloop in exception and error handlers
  src/ext/lifecycle.c
Labels: agent-php

#966 fix: add docker container id discovery for SystemData
  src/ElasticApm/Impl/MetadataDiscoverer.php
  src/ElasticApm/Impl/SystemData.php
  tests/ElasticApmTests/UnitTests/MetadataTest.php
  tests/ElasticApmTests/Util/Deserialization/MetadataDeserializer.php
Labels: agent-php

#407 Added dev_internal_backend_comm_log_verbose to use CURLOPT_VERBOSE on demand
  docs/troubleshooting.asciidoc
  src/ext/ConfigManager.c
  src/ext/ConfigManager.h
  src/ext/ConfigSnapshot.h
  src/ext/backend_comm.c
  src/ext/elastic_apm.c
  src/ext/util.h
Labels: agent-php

#972 Fixed default in documentation for dev_internal_backend_comm_log_verbose
  docs/troubleshooting.asciidoc
Labels: agent-php

#960 Fixed not unregistering signal handler on module shutdown
  src/ext/lifecycle.c
  src/ext/platform.c
  src/ext/platform.h
Labels: agent-php

#973 Simplified logging of the current process command line
  src/ext/StringView.h
  src/ext/backend_comm.c
  src/ext/platform.c
  src/ext/platform.h
  src/ext/unit_tests/platform_tests.c
  src/ext/unit_tests/unit_test_util.h
Labels: supportability

#975 Fixed metadata container ID detected but not stored
  .ci/run_docker_with_component_tests.sh
  composer.json
  docs/configuration.asciidoc
  src/ElasticApm/Impl/Config/NullableBoolOptionMetadata.php
  src/ElasticApm/Impl/MetadataDiscoverer.php
  tests/ElasticApmTests/ComponentTests/MetadataDiscovererComponentTest.php
  tests/ElasticApmTests/ComponentTests/Util/AllComponentTestsOptionsMetadata.php
  tests/ElasticApmTests/ComponentTests/Util/ConfigSnapshotForTests.php
  tests/ElasticApmTests/ComponentTests/Util/DataFromAgentPlusRawExpectations.php
  tests/ElasticApmTests/ComponentTests/Util/DataFromAgentPlusRawValidator.php
  tests/ElasticApmTests/ComponentTests/Util/DockerUtil.php
  tests/ElasticApmTests/UnitTests/MetadataDiscovererUnitTest.php
  tests/ElasticApmTests/Util/MetadataExpectations.php
  tests/ElasticApmTests/Util/MetadataValidator.php
Labels: agent-php

#979 Run composer install with retries for unit tests as well
  .ci/shared.sh
  .ci/static-check-unit-test.sh
  .ci/validate_agent_installation.sh
Labels: agent-php

#976 Enabled modern build in github actions
  .ci/Makefile
  .ci/bump_version.sh
  .ci/generate-for-package.sh
  .ci/run-phpt-tests.sh
  .ci/static-check-unit-test.sh
  .github/workflows/release.yml
  .github/workflows/test.yml
  DEVELOPMENT.md
  Dockerfile
  Dockerfile.alpine
  agent/native/CMakeLists.txt
  agent/native/building/dockerized/docker-compose.yml
  agent/native/ext/CMakeLists.txt
  agent/native/ext/numbered_intercepting_callbacks.h
  agent/native/ext/tests/config_boolean_0_using_env_var_is_false.phpt
  agent/native/ext/tests/config_boolean_0_using_ini_is_false.phpt
  agent/native/ext/tests/config_boolean_1_using_env_var_is_true.phpt
  agent/native/ext/tests/config_boolean_1_using_ini_is_true.phpt
  agent/native/ext/tests/config_boolean_FaLSe_using_env_var_is_false.phpt
  agent/native/ext/tests/config_boolean_FaLSe_using_ini_is_false.phpt
  agent/native/ext/tests/config_boolean_No_using_env_var_is_false.phpt
  agent/native/ext/tests/config_boolean_No_using_ini_is_false.phpt
  agent/native/ext/tests/config_boolean_OFF_using_env_var_is_false.phpt
  agent/native/ext/tests/config_boolean_OFF_using_ini_is_false.phpt
  agent/native/ext/tests/config_boolean_TRue_using_env_var_is_true.phpt
  agent/native/ext/tests/config_boolean_TRue_using_ini_is_true.phpt
  agent/native/ext/tests/config_boolean_oN_using_env_var_is_true.phpt
  agent/native/ext/tests/config_boolean_oN_using_ini_is_true.phpt
  agent/native/ext/tests/config_boolean_yEs_using_env_var_is_true.phpt
  agent/native/ext/tests/config_boolean_yEs_using_ini_is_true.phpt
  agent/native/ext/tests/config_defaults.phpt
  agent/native/ext/tests/config_dynamic_options.phpt
  agent/native/ext/tests/config_enabled_ini_setting_cannot_be_changed_after_start.phpt
  agent/native/ext/tests/config_ini_has_higher_precedence_than_env_vars.phpt
  agent/native/ext/tests/config_invalid_ini_fallback_default_not_env_var.phpt
  agent/native/ext/tests/config_setting_to_invalid_values_using_env_vars.phpt
  agent/native/ext/tests/config_setting_to_invalid_values_using_ini.phpt
  agent/native/ext/tests/config_setting_to_non-defaults_using_env_vars.phpt
  agent/native/ext/tests/config_setting_to_non-defaults_using_ini.phpt
  agent/native/ext/tests/config_type_LogLevel_is_case_insensitive.phpt
  agent/native/ext/tests/config_type_LogLevel_unambiguous_prefix_is_enough.phpt
  agent/native/ext/tests/opcache_preload_detection.phpt
  agent/native/ext/tests/opcache_preload_detection_double.phpt
  agent/native/ext/tests_util/tests_util.php
  agent/native/ext/unit_tests/gen_numbered_intercepting_callbacks_src.h
  agent/php/ElasticApm/Impl/Config/Snapshot.php
  composer.json
  demos/shared/install_agent.sh
  packaging/Makefile
  packaging/before-uninstall.sh
  packaging/create-package.sh
  packaging/post-install.sh
  packaging/test/centos/entrypoint.sh
  packaging/test/ubuntu/entrypoint.sh
Labels: agent-php
